import type { Metadata } from "next";
import "./globals.css";
import { type ReactNode } from "react"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "TSender",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: ReactNode}) {
  return (
    <html lang="en">
      <body>
        Hi from layout~!!!

        <Providers>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
